DROP TABLE IF EXISTS PURCHASE_ORDER;

CREATE TABLE PURCHASE_ORDER (
    ID INTEGER IDENTITY PRIMARY KEY,
    SHIPPING_ADDRESS VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS ORDER_ITEM;

CREATE TABLE ORDER_ITEM (
    PURCHASE_ORDER INTEGER,
    QUANTITY INTEGER NOT NULL,
    PRODUCT VARCHAR(128) NOT NULL
);


