DROP SCHEMA IF EXISTS BASICS_SCHEMA;

CREATE schema IF NOT EXISTS BASICS_SCHEMA;
USE BASICS_SCHEMA;

DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
    ID INTEGER IDENTITY PRIMARY KEY,
    NAME VARCHAR(256) NOT NULL,
    ISBN VARCHAR(16) NOT NULL,
    PRICE DECIMAL(10,2) NOT NULL,
    PUBLISHED_DATE DATE NOT NULL
);

DROP TABLE IF EXISTS PERSON;

CREATE TABLE PERSON (
    ID INTEGER IDENTITY PRIMARY KEY,
    FIRST_NAME VARCHAR(256) NOT NULL,
    LAST_NAME VARCHAR(256) NOT NULL
);

DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
	ID INTEGER IDENTITY PRIMARY KEY,
	USER_NAME VARCHAR(45) NOT NULL,
	PASSWORD VARCHAR(45) NOT NULL,
	EMAIL VARCHAR(100) DEFAULT NULL,
	CREATED_TIME DATETIME NOT NULL,
	UPDATED_TIME DATETIME DEFAULT NULL,
	USER_TYPE VARCHAR(45) NOT NULL,
	DOB DATE NOT NULL
);

-- Data

