CREATE TABLE `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(45) DEFAULT NULL,
  `LAST_NAME` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(45) DEFAULT NULL,
  `PASSWORD` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `PRIVILEGE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);


CREATE TABLE `ROLE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `ROLE_PRIVILEGE` (
  `ROLE_ID` int(11),
  `PRIVILEGE_ID` int(11),
  PRIMARY KEY (`ROLE_ID`,`PRIVILEGE_ID`),
  CONSTRAINT `ROLE_PRIV_ID_FK` 
     FOREIGN KEY (`ROLE_ID`) 
     REFERENCES `ROLE` (`ID`),
  CONSTRAINT `PRIVILEGE_ROLE_ID_FK` 
     FOREIGN KEY (`PRIVILEGE_ID`) 
     REFERENCES `PRIVILEGE` (`ID`)
);

CREATE TABLE `USER_ROLE` (
  `USER_ID` int(11),
  `ROLE_ID` int(11),
  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  CONSTRAINT `USER_ROLE_ID_FK` 
     FOREIGN KEY (`USER_ID`) 
     REFERENCES `USER` (`ID`),
  CONSTRAINT `ROLE_USER_ID_FK` 
     FOREIGN KEY (`ROLE_ID`) 
     REFERENCES `ROLE` (`ID`)
);


